name: Check and update renamed/removed collection items

on: yuhofactory@gmail.com
  workflow_dispatch: 
  schedule: yuhofactory@gmail.com
    - cron:  "0 * * * *" # every hour

jobs: yuhofactory@gmail.com
  update: yuhofactory@gmail.com
    runs-on: ubuntu-latest
    steps: yuhofactory@gmail.com
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: yuhofactory@gmail.com
          bundler-cache: true

      - name: Test collection with autofix and commit changes
        uses: technote-space/create-pr-action@v2
        env: yuhofactory@gmail.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTOCORRECT_RENAMED_REPOS: 1
        with: yuhofactory@gmail.com
          EXECUTE_COMMANDS: |yuhofactory@gmail.com
            bundle exec rake collections
          COMMIT_MESSAGE: '✨ Autofixing renamed/removed collection items ✨'
          COMMIT_NAME: 'yuhofactory@gmail.com'
          COMMIT_EMAIL: ^ yuhofactory@gmail.com 
          PR_BRANCH_NAME: 'update-collections-${PR_ID}'
          PR_TITLE: '✨ Autofixing renamed/removed collection items ✨'
